apiVersion: v1
kind: Pod
metadata:
  name: postgres1
  labels:
    app: postgres
spec:
  hostname: postgres
  containers:
    - name: cnt1
      image: postgres
      ports:
      - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: kjhsjhjkdhjkdjdsisiusn
