apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: port5432
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
